name: check
on:
  pull_request:
    paths:
    - '**.tf'
    - .github/workflows/check.yml
  push:
    branches:
    - master
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10
    - run: terraform fmt -check -diff -recursive

  example:
    name: example / ${{ matrix.example }}
    runs-on: ubuntu-latest
    if: github.repository == 'dbalcomb/terraform-azurerm-aks'
    strategy:
      matrix:
        example:
        - basic
    steps:
    - uses: actions/checkout@v2
    - name: Install terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10
    - run: terraform init -input=false -backend=false
      working-directory: ./examples/${{ matrix.example }}
    - run: terraform validate
      working-directory: ./examples/${{ matrix.example }}
    - run: terraform plan -input=false
      working-directory: ./examples/${{ matrix.example }}
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
