name: check
on:
  pull_request:
    paths:
    - '**.tf'
    - .github/workflows/check.yml
  push:
    branches:
    - master
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volcano-coffee-company/setup-terraform@v1
      with:
        version: ~0.12
    - run: terraform init -backend=false
    - run: terraform validate
